server:
        port: 8081
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/student1133
    username: root
    password: ponleu
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  mvc:
    pathmatch:
         matching-strategy: ANT_PATH_MATCHER
  jackson:
    serialization:
      fail-on-empty-beans: false
  liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml
      
      